/*******************************************************************************
 * Copyright (c) 2011, 2012, 2013 EnergyOS.Org
 *
 * Licensed by EnergyOS.Org under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.  The EnergyOS.org licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at:
 *  
 *   http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 *  
 ******************************************************************************
*/


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.24 at 10:28:07 AM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://naesb.org/espi", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
@XmlJavaTypeAdapters({

	@XmlJavaTypeAdapter(type=AccumulationBehavior.class, value=AccumulationBehaviorAdapter.class),
	@XmlJavaTypeAdapter(type=AuthorizationStatus.class, value=AuthorizationStatusAdapter.class),
	@XmlJavaTypeAdapter(type=CPP.class, value=CPPAdapter.class),
	@XmlJavaTypeAdapter(type=CRUDOperation.class, value=CRUDOperationAdapter.class),
	@XmlJavaTypeAdapter(type=Commodity.class, value=CommodityAdapter.class),
	@XmlJavaTypeAdapter(type=ConsumptionTier.class, value=ConsumptionTierAdapter.class),
	@XmlJavaTypeAdapter(type=Currency.class, value=CurrencyAdapter.class),
	@XmlJavaTypeAdapter(type=DataCustodianApplicationStatus.class, value=DataCustodianApplicationStatusAdapter.class),
	@XmlJavaTypeAdapter(type=DataCustodianType.class, value=DataCustodianTypeAdapter.class),
	@XmlJavaTypeAdapter(type=DataQualifier.class, value=DataQualifierAdapter.class),
	@XmlJavaTypeAdapter(type=DirectionOfFlow.class, value=DirectionOfFlowAdapter.class),
	@XmlJavaTypeAdapter(type=Kind.class, value=KindAdapter.class),
	@XmlJavaTypeAdapter(type=PhaseCode.class, value=PhaseCodeAdapter.class),
	@XmlJavaTypeAdapter(type=QualityOfReading.class, value=QualityOfReadingAdapter.class),
	@XmlJavaTypeAdapter(type=ServiceKind.class, value=ServiceKindAdapter.class),
	@XmlJavaTypeAdapter(type=ServiceStatus.class, value=ServiceStatusAdapter.class),
	@XmlJavaTypeAdapter(type=StatusCode.class, value=StatusCodeAdapter.class),
	@XmlJavaTypeAdapter(type=ThirdPartyApplicationStatus.class, value=ThirdPartyApplicationStatusAdapter.class),
	@XmlJavaTypeAdapter(type=ThirdPartyApplicationType.class, value=ThirdPartyApplicationTypeAdapter.class),
	@XmlJavaTypeAdapter(type=ThirdPartyApplicationUse.class, value=ThirdPartyApplicationUseAdapter.class),
	@XmlJavaTypeAdapter(type=TimeAttribute.class, value=TimeAttributeAdapter.class),
	@XmlJavaTypeAdapter(type=TimePeriodOfInterest.class, value=TimePeriodOfInterestAdapter.class),
	@XmlJavaTypeAdapter(type=TOU.class, value=TOUAdapter.class),
	@XmlJavaTypeAdapter(type=UnitMultiplier.class, value=UnitMultiplierAdapter.class),
	@XmlJavaTypeAdapter(type=UnitSymbol.class, value=UnitSymbolAdapter.class),
	@XmlJavaTypeAdapter(type=UsagePoint.class, value = UsagePointAdapter.class)	
	
})

package org.energyos.espi.datacustodian.common;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapters;

